global:
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

postgresql:
  enabled: true
  persistence:
    size: 5Gi

artifactory:
  enabled: true
  artifactory:
#    unifiedSecretInstallation: true
#    unifiedSecretPrependReleaseName: true
    persistence:
      size: 2Gi
